In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
%matplotlib inline

In [2]:
df=pd.read_csv("Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
df["Exited"].value_counts()
df["Gender"].value_counts()
df["Geography"].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [4]:
df.drop(columns=["RowNumber","CustomerId","Surname"], inplace=True)

In [5]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
df=pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split the data into features (X) and target variable (y)
X = df.drop(columns=["Exited"])
y = df["Exited"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# Initialize StandardScaler
scaler = StandardScaler()

# Scale the training data
X_train_scaled = scaler.fit_transform(X_train)

# Scale the testing data using the same scaler from training data
X_test_scaled = scaler.transform(X_test)

# scale during weight trainign for better convergence

In [8]:
# Start makin model

In [9]:
import tensorflow as tf
from tensorflow import keras

# Corrected import for Sequential
from tensorflow.keras.models import Sequential

# Corrected import for Dense
from tensorflow.keras.layers import Dense

In [10]:
# Initialize the Sequential model
model = Sequential()

# Add the first Dense layer with 3 units, sigmoid activation, and input dimension 11
model.add(Dense(3, activation="sigmoid", input_dim=11))

# Add the second Dense layer with 1 unit and sigmoid activation
model.add(Dense(1, activation="sigmoid"))

C:\Users\Sagar Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 3)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.compile(loss="binary_crossentropy",optimizer="adam")

In [32]:
model.fit(X_train_scaled,y_train,epochs=10,batch_size=800,validation_split=0.2)

Epoch 1/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.4090 - val_loss: 0.4017
Epoch 2/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4095 - val_loss: 0.4017
Epoch 3/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4052 - val_loss: 0.4017
Epoch 4/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.4078 - val_loss: 0.4017
Epoch 5/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4093 - val_loss: 0.4017
Epoch 6/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4036 - val_loss: 0.4017
Epoch 7/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4021 - val_loss: 0.4017
Epoch 8/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.4077 - val_loss: 0.4017
Epoch 9/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4094 - val_loss: 0.4017
Epoch 10/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4017 - val_loss: 0.4017

In [27]:
model.layers[0].get_weights()

[array([[ 0.3111926 , -0.11768437,  0.1209611 ],
        [-2.7657325 , -0.06920687,  3.6513803 ],
        [-0.0554602 ,  0.08773874,  0.03270201],
        [ 0.02507146, -0.41184622,  0.29789266],
        [ 0.0345358 ,  0.4153053 ,  0.04206054],
        [-0.10141407, -0.04747528, -0.0711234 ],
        [-0.78276545,  2.3387818 ,  0.65947205],
        [ 0.15561959, -0.25480402, -0.14197649],
        [-0.5629424 , -1.0973568 , -0.48446953],
        [-0.22729231, -0.15355045, -0.37569496],
        [ 0.33306378,  0.6800532 , -0.09651656]], dtype=float32),
 array([ 0.15105304,  0.59352505, -0.762589  ], dtype=float32)]

In [28]:
model.layers[1].get_weights()

[array([[-1.7887344],
        [-2.132795 ],
        [ 1.1062769]], dtype=float32),
 array([0.07961098], dtype=float32)]

In [29]:
y_log=model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [30]:
y_pred=np.where(y_log>0.5,1,0)

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8035